# Introduction to PyTorch

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = torch.ones(3, 2)
print(x)
x = torch.zeros(3, 2)
print(x)
x = torch.rand(3, 2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.3838, 0.5630],
        [0.6901, 0.2992],
        [0.6091, 0.0553]])


# Numpy vs Pytorch

#### Matrix Multiplication using numpy

In [3]:
%%time
for i in range(100):
  a = np.random.randn(1000,1000)
  b = np.random.randn(1000,1000)
  c = np.matmul(a, b)

CPU times: user 17 s, sys: 8.42 s, total: 25.4 s
Wall time: 13 s


#### Matrix Multiplication using PyTorch and GPU

In [4]:
cuda0 = torch.device('cuda:0')
a = torch.ones(3, 2, device=cuda0)
b = torch.ones(3, 2, device=cuda0)

In [5]:
%%time
for i in range(100):
  a = torch.randn([1000, 1000], device=cuda0)
  b = torch.randn([1000, 1000], device=cuda0)
  torch.matmul(a, b)

CPU times: user 4.8 ms, sys: 1.41 ms, total: 6.21 ms
Wall time: 22.5 ms


# AutoDiff

In [6]:
x = torch.ones([3, 2], requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [7]:
y = x + 5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [8]:
z = y*y + 1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [9]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [10]:
t.backward()

In [11]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


$t = \sum_i z_i, z_i = y_i^2 + 1, y_i = x_i + 5$

$\frac{\partial t}{\partial x_i} = \frac{\partial z_i}{\partial x_i} = \frac{\partial z_i}{\partial y_i} \frac{\partial y_i}{\partial x_i} = 2y_i \times 1$


At x = 1, y = 6, $\frac{\partial t}{\partial x_i} = 12$

## Please feel free to interact... sivaharivkm@gmail.com