#Google colab and python basics

In [1]:
!ls

sample_data


In [0]:
!touch abc

In [3]:
!ls

abc  sample_data


In [4]:
print ('hello world')

hello world


In [5]:
name = 'redmi note 7 pro'
type(name)

str

In [6]:
no_of_cams = 1
type(no_of_cams)

int

In [7]:
ver = 2.3
type(ver)

float

In [8]:
nos = [1,2,3,4,5,6,7,8,9]
type(nos)
print("first no is",nos[0])

first no is 1


In [9]:
myphone = {"os":"Android","make":"Redmi","model":"Note 7 Pro"}
type(myphone)
print('my phone is ',myphone["make"])

my phone is  Redmi


In [10]:
a = 10
if a>5 :
  print('a is greater')
  print('this line is also in if')
else :
  print('a is smaller')

a is greater
this line is also in if


In [11]:
for i in range(5):
  print (i)

0
1
2
3
4


In [0]:
def my_function():
  print('this is my first function')

In [13]:
my_function()

this is my first function


In [0]:
def findsum(a,b,c=0):
  return a+b+c
  

In [15]:
print(findsum(10,5,10))

25


#Numpy Introduction

In [0]:
import numpy as np

In [18]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [22]:
b = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [23]:
print(b.shape)

(3, 3)


In [28]:
print(b[0,:])

[1 2 3]


In [30]:
print(b[:,1])

[2 5 9]


In [31]:
print(b[0,0:2])

[1 2]


In [32]:
print(b.shape)

(3, 3)


In [0]:
c = np.array([[1,2,3],[4,5,6]])

In [35]:
print(c.shape)
print(c)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [41]:
d = c.reshape((3,2))
print(d)


[[1 2]
 [3 4]
 [5 6]]


In [40]:
print(d.shape)

(3, 2)


In [45]:
print(d)
dt = d.transpose()
print("transpose is")
print(dt)

[[1 2]
 [3 4]
 [5 6]]
transpose is
[[1 3 5]
 [2 4 6]]


In [53]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2,3],[4,5,6]])
print(x.shape,y.shape)
z = np.dot(x,y)
print(z)

(2, 2) (2, 3)
[[ 9 12 15]
 [19 26 33]]


In [55]:
!cat phones.csv

1,8500
2,7000
3,12500
4,17500


In [60]:
data = np.loadtxt(open("phones.csv","rb"),delimiter=",")
print(data[0,1])

8500.0
