In [0]:
import numpy as np

In [8]:
a=np.array([[1,2,3],[4,5,6]])

ERROR! Session/line number was not unique in database. History logging moved to new session 60


In [10]:
np.column_stack((a,[7,8]))

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [12]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
y=np.array([[1,2,3],[4,5,6]])
y.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
!ls

phones.csv  sample_data


In [20]:
data =np.loadtxt(open("phones.csv","rb"), delimiter = ',')
data[1,1]

700.0